export const screenX = document.querySelector("#valorx"),
  screenY = document.querySelector("#valory"),
  background = document.querySelector("#background"),
  frontSize = document.querySelector("#font_size"),
  screenColor = document.querySelector("#Color"),
  screenName = document.querySelector("#name"),
  border = document.querySelector("#border"),
  border_radio = document.querySelector("#border_radius"),
  pai = document.querySelector("#stopbutton"),
  editer = document.querySelector("#edite"),
  delet = document.querySelector("#delete"),
  status = document.querySelector("#status"),
  inputcreate = document.querySelector("#input"),
  pesquisa = document.querySelector("#barPesquisa"),
  onoffedito = document.querySelector("#editotxt"),
  acitiveEditotxt = document.querySelector(".activetxt"),
  desenbledEditotxt = document.querySelector(".desenabled"),
  menustatus = document.querySelector("#menuStatus"),
  inputObj = [
    "p",
    "div",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "button",
    "html",
    "body",
    "main",
    "section",
    "article",
    "nav",
    "aside",
    "header",
    "footer",
    "ul",
    "ol",
    "li",
    "dl",
    "dt",
    "dd",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "td",
    "th",
    "a",
    "canvas",
    "svg",
    "object",
    "video",
    "audio",
    "iframe",
    "picture",
    "script",
    "noscript",
    "details",
    "summary",
    "span",
    "dialog",
  ],
  inputSpecific = ["img", "source", "track", "embed", "wbr"],
  formatDualTag = [
    "b",
    "strong",
    "i",
    "em",
    "mark",
    "small",
    "del",
    "ins",
    "sub",
    "sup",
    "u",
    "abbr",
    "code",
    "kbd",
    "samp",
    "var",
    "q",
    "blockquote",
    "cite",
    "pre",
  ],
  formatOneTag = ["br", "hr"],
  armazepos = { x: 0, y: 0 },
  select = { selet: null },
  armaze = { armaz: [] };
